const initialDeck = [ 
    { value: "2", type: "S"},
    { value: "3", type: "S"},
    { value: "4", type: "S"},
    { value: "5", type: "S"},
    { value: "6", type: "S"},
    { value: "7", type: "S"},
    { value: "8", type: "S"},
    { value: "9", type: "S"},
    { value: "T", type: "S"},
    { value: "J", type: "S"},
    { value: "Q", type: "S"},
    { value: "K", type: "S"},
    { value: "A", type: "S"},

    { value: "2", type: "D" },
    { value: "3", type: "D" },
    { value: "4", type: "D" },
    { value: "5", type: "D" },
    { value: "6", type: "D" },
    { value: "7", type: "D" },
    { value: "8", type: "D" },
    { value: "9", type: "D" },
    { value: "T", type: "D" },
    { value: "J", type: "D" },
    { value: "Q", type: "D" },
    { value: "K", type: "D" },
    { value: "A", type: "D" },

    { value: "2", type: "C" },
    { value: "3", type: "C" },
    { value: "4", type: "C" },
    { value: "5", type: "C" },
    { value: "6", type: "C" },
    { value: "7", type: "C" },
    { value: "8", type: "C" },
    { value: "9", type: "C" },
    { value: "T", type: "C" },
    { value: "J", type: "C" },
    { value: "Q", type: "C" },
    { value: "K", type: "C" },
    { value: "A", type: "C" },

    { value: "2", type: "H" },
    { value: "3", type: "H" },
    { value: "4", type: "H" },
    { value: "5", type: "H" },
    { value: "6", type: "H" },
    { value: "7", type: "H" },
    { value: "8", type: "H" },
    { value: "9", type: "H" },
    { value: "T", type: "H" },
    { value: "J", type: "H" },
    { value: "Q", type: "H" },
    { value: "K", type: "H" },
    { value: "A", type: "H" }, 
]

export default initialDeck